"""esquema inicial

Revision ID: 639d4d737621
Revises: 
Create Date: 2026-09-23 22:51:48.452606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639d4d737621'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id_matricula', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('status_atividade', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('graduacao_atual', sa.String(), nullable=True),
    sa.Column('data_ultima_graduacao', sa.Date(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('nacionalidade', sa.String(), nullable=True),
    sa.Column('naturalidade', sa.String(), nullable=True),
    sa.Column('nome_pai', sa.String(), nullable=True),
    sa.Column('nome_mae', sa.String(), nullable=True),
    sa.Column('contato_emergencia_nome', sa.String(), nullable=True),
    sa.Column('contato_emergencia_parentesco', sa.String(), nullable=True),
    sa.Column('contato_emergencia_telefone', sa.String(), nullable=True),
    sa.Column('historico_marcial', sa.String(), nullable=True),
    sa.Column('equipamento_proprio', sa.Boolean(), nullable=True),
    sa.Column('termo_risco_assinado', sa.Boolean(), nullable=True),
    sa.Column('restricao_medica', sa.String(), nullable=True),
    sa.Column('autorizacao_imagem', sa.Boolean(), nullable=True),
    sa.Column('hora_flexivel', sa.Boolean(), nullable=True),
    sa.Column('diario_pedagogico', sa.String(), nullable=True),
    sa.Column('modo_treino', sa.String(), nullable=True),
    sa.Column('acordo_contratual', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_matricula')
    )
    op.create_index(op.f('ix_alunos_id_matricula'), 'alunos', ['id_matricula'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', sa.String(), nullable=True),
    sa.Column('modelo_plano', sa.String(), nullable=True),
    sa.Column('valor_base', sa.Float(), nullable=True),
    sa.Column('valor_contratual_fixo', sa.Float(), nullable=True),
    sa.Column('taxa_admissao_saldo', sa.Float(), nullable=True),
    sa.Column('horas_franquia', sa.Integer(), nullable=True),
    sa.Column('observacao_financeira', sa.String(), nullable=True),
    sa.Column('inclui_shokubai', sa.Boolean(), nullable=True),
    sa.Column('dia_vencimento', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_id'), 'contratos', ['id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', sa.String(), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('metodo', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_id'), 'pagamentos', ['id'], unique=False)
    op.create_table('presencas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_aluno', sa.String(), nullable=True),
    sa.Column('hora_entrada', sa.DateTime(), nullable=True),
    sa.Column('hora_saida', sa.DateTime(), nullable=True),
    sa.Column('valor_apurado', sa.Float(), nullable=True),
    sa.Column('desconto_aplicado', sa.Float(), nullable=True),
    sa.Column('diario_sensei', sa.String(), nullable=True),
    sa.Column('pago', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['alunos.id_matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_id'), 'sessoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessoes_id'), table_name='sessoes')
    op.drop_table('sessoes')
    op.drop_table('presencas')
    op.drop_index(op.f('ix_pagamentos_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_contratos_id'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_alunos_id_matricula'), table_name='alunos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
